const fs = require('fs');
const lines = [];
const p = (s) => lines.push(s);
p(import React, { useState, useEffect, useRef } from "react";);
p(import { useQuery, useMutation, useAction } from "convex/react";);
p(import { useUser, useClerk } from "@clerk/clerk-react";);
p(import { api } from "../../../convex/_generated/api";);
p(`);
p(	ype Tab = "overview" | "accounts" | "plans" | "features" | "notifications" | "billing" | "integrations" | "tickets" | "templates" | "health" | "audit" | "settings";);
p(	ype Plan = "free" | "pro" | "enterprise" | "custom";);
p(	ype OrgStatus = "active" | "trial" | "blocked" | "suspended";);
p(	ype Theme = "dark" | "light";);
p(`);
p(const T = {);
p(  dark: { bg:"#0a0c0f",surface:"#111318",surfaceEl:"#181c23",border:"#232830",borderHov:"#2e3542",text:"#f0f2f5",textSub:"#8b92a0",textMute:"#4a5261",accent:"#22c55e",accentDim:"#166534",accentBg:"#0d2018",danger:"#ef4444",dangerBg:"#2a1212",warn:"#f59e0b",warnBg:"#251c08",info:"#38bdf8",infoBg:"#081c28",purple:"#a78bfa",purpleBg:"#1a1330" },);
p(  light: { bg:"#f4f6f9",surface:"#ffffff",surfaceEl:"#f9fafb",border:"#e5e7eb",borderHov:"#d1d5db",text:"#111827",textSub:"#6b7280",textMute:"#9ca3af",accent:"#16a34a",accentDim:"#bbf7d0",accentBg:"#f0fdf4",danger:"#dc2626",dangerBg:"#fef2f2",warn:"#d97706",warnBg:"#fffbeb",info:"#0369a1",infoBg:"#f0f9ff",purple:"#7c3aed",purpleBg:"#f5f3ff" },);
p(} as const;);
p(`);
p(const IcoGrid=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>;);
p(const IcoUsers=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>;);
p(const IcoSliders=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><line x1="4" y1="6" x2="20" y2="6"/><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="18" x2="20" y2="18"/><circle cx="8" cy="6" r="2" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r="2" fill="currentColor" stroke="none"/><circle cx="10" cy="18" r="2" fill="currentColor" stroke="none"/></svg>;);
p(const IcoLog=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>;);
p(const IcoDollar=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>;);
p(const IcoGear=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>;);
p(const IcoPlus=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>;);
p(const IcoSearch=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>;);
p(const IcoTrash=()=><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/></svg>;);
p(const IcoLogout=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>;);
p(const IcoClose=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>;);
p(const IcoCheck=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>;);
p(const IcoChevR=()=><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="9 18 15 12 9 6"/></svg>;);
p(const IcoSun=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>;);
p(const IcoMoon=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>;);
p(const IcoUpload=()=><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/></svg>;);
p(const IcoEdit=()=><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>;);
p(const IcoShield=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>;);
p(const IcoBell=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>;);
p(const IcoCreditCard=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>;);
p(const IcoZap=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>;);
p(const IcoTicket=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"/></svg>;);
p(const IcoLayout=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="9" y1="21" x2="9" y2="9"/></svg>;);
p(const IcoActivity=()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>;);
p(`);
p(const FEATURES = [);
p(  { key:"checkInEnabled",        label:"Check-in",       desc:"Visitor check-in kiosk" },);
p(  { key:"schedulingEnabled",     label:"Scheduling",     desc:"Pre-scheduled visits" },);
p(  { key:"messagingEnabled",      label:"Messaging",      desc:"Staff messaging" },);
p(  { key:"analyticsEnabled",      label:"Analytics",      desc:"Visitor reports" },);
p(  { key:"badgesEnabled",         label:"Badges",         desc:"Visitor badges" },);
p(  { key:"notificationsEnabled",  label:"Notifications",  desc:"Email and push alerts" },);
p(  { key:"attendanceEnabled",     label:"Attendance",     desc:"Clock-in/out" },);
p(  { key:"multiLocationEnabled",  label:"Multi-site",     desc:"Multiple locations" },);
p(  { key:"apiAccessEnabled",      label:"API",            desc:"REST API access" },);
p(  { key:"ssoEnabled",            label:"SSO",            desc:"Single sign-on" },);
p(  { key:"whitelabelEnabled",     label:"Whitelabel",     desc:"Custom branding" },);
p(  { key:"dedicatedSupportEnabled",label:"Ded. support",  desc:"Dedicated support" },);
p(];);
p(`);
p(const DEFAULT_FEATURES_BY_PLAN: Record<string,Record<string,boolean>> = {);
p(  free:       {checkInEnabled:true,badgesEnabled:false,schedulingEnabled:false,messagingEnabled:false,analyticsEnabled:false,notificationsEnabled:false,attendanceEnabled:false,multiLocationEnabled:false,apiAccessEnabled:false,ssoEnabled:false,whitelabelEnabled:false,dedicatedSupportEnabled:false},);
p(  pro:        {checkInEnabled:true,badgesEnabled:true,schedulingEnabled:true,messagingEnabled:true,analyticsEnabled:true,notificationsEnabled:true,attendanceEnabled:true,multiLocationEnabled:false,apiAccessEnabled:false,ssoEnabled:false,whitelabelEnabled:false,dedicatedSupportEnabled:false},);
p(  enterprise: {checkInEnabled:true,badgesEnabled:true,schedulingEnabled:true,messagingEnabled:true,analyticsEnabled:true,notificationsEnabled:true,attendanceEnabled:true,multiLocationEnabled:true,apiAccessEnabled:true,ssoEnabled:true,whitelabelEnabled:true,dedicatedSupportEnabled:true},);
p(  custom:     {checkInEnabled:true,badgesEnabled:true,schedulingEnabled:true,messagingEnabled:true,analyticsEnabled:true,notificationsEnabled:true,attendanceEnabled:true,multiLocationEnabled:true,apiAccessEnabled:true,ssoEnabled:true,whitelabelEnabled:true,dedicatedSupportEnabled:true},);
p(};);
p(`);
p(const DEFAULT_PLANS = [);
p(  {id:"free",       name:"Free",       price:0,   annualPrice:0,   maxUsers:5,   maxLocations:1,  color:"#6b7280",desc:"For small teams getting started",  features:DEFAULT_FEATURES_BY_PLAN.free},);
p(  {id:"pro",        name:"Pro",        price:49,  annualPrice:39,  maxUsers:50,  maxLocations:5,  color:"#22c55e",desc:"For growing organisations",         features:DEFAULT_FEATURES_BY_PLAN.pro},);
p(  {id:"enterprise", name:"Enterprise", price:199, annualPrice:159, maxUsers:999, maxLocations:99, color:"#f59e0b",desc:"For large enterprises",             features:DEFAULT_FEATURES_BY_PLAN.enterprise},);
p(  {id:"custom",     name:"Custom",     price:0,   annualPrice:0,   maxUsers:999, maxLocations:999,color:"#a78bfa",desc:"Negotiated pricing",                features:DEFAULT_FEATURES_BY_PLAN.custom},);
p(];);
p(`);
p(const COMING_SOON_ITEMS: Record<string,{icon:string;label:string;detail:string}[]> = {);
p(  "Notifications":[{icon:"X1",label:"Email templates",detail:"Customise transactional emails sent to admins and visitors"},{icon:"X2",label:"SMS / WhatsApp alerts",detail:"Configure WhatsApp and SMS notification triggers per org"},{icon:"X3",label:"Push notifications",detail:"Browser and mobile push for real-time alerts"},{icon:"X4",label:"Webhook delivery",detail:"Send events to external URLs on check-in, booking changes etc"}],);
p(  "Billing":[{icon:"X1",label:"Stripe integration",detail:"Connect Stripe to auto-charge orgs based on their plan"},{icon:"X2",label:"Invoices",detail:"Generate and send monthly invoices to org owners"},{icon:"X3",label:"Revenue analytics",detail:"MRR, churn rate, upgrades and downgrades over time"},{icon:"X4",label:"Dunning management",detail:"Automated retries and grace-period handling for failed payments"}],);
p(  "Integrations":[{icon:"X1",label:"Zapier / Make",detail:"No-code automation triggers for check-in and scheduling events"},{icon:"X2",label:"Google Calendar",detail:"Sync scheduled visits with Google Calendar for hosts"},{icon:"X3",label:"Slack",detail:"Post visitor arrivals and alerts to Slack channels"},{icon:"X4",label:"SAML SSO",detail:"Enterprise SSO via Okta, Azure AD, and SAML providers"}],);
p(  "Support Tickets":[{icon:"X1",label:"Ticket inbox",detail:"Receive and triage support requests from org admins"},{icon:"X2",label:"AI triage",detail:"Auto-categorise and prioritise incoming tickets"},{icon:"X3",label:"SLA tracking",detail:"Monitor response and resolution times by plan tier"},{icon:"X4",label:"Knowledge base",detail:"Build a help centre linked from admin and staff portals"}],);
p(  "Templates":[{icon:"X1",label:"Email templates",detail:"Reusable email layouts for invites, reminders, and confirmations"},{icon:"X2",label:"Badge templates",detail:"Design visitor badge layouts per organisation or globally"},{icon:"X3",label:"Check-in form presets",detail:"Save and reuse check-in field configurations across orgs"},{icon:"X4",label:"Document templates",detail:"NDA and policy templates presented at check-in"}],);
p(  "System Health":[{icon:"X1",label:"Service status",detail:"Live uptime indicators for Convex, Clerk, and edge functions"},{icon:"X2",label:"Performance metrics",detail:"P50/P95 query latency and function execution times"},{icon:"X3",label:"Error tracking",detail:"Aggregated error rates and stack traces from all functions"},{icon:"X4",label:"Database usage",detail:"Table sizes, index usage, and storage consumption per org"}],);
p(};);
p(`);
p(unction useTheme(){);
p(  const [theme,setTheme]=React.useState<Theme>(()=>{try{return(localStorage.getItem("porta-sa-theme") as Theme)||"dark";}catch{return"dark";}}););
p(  const toggle=()=>setTheme(t=>{const n=t==="dark"?"light":"dark";try{localStorage.setItem("porta-sa-theme",n);}catch{}return n;}););
p(  return {theme,toggle,c:T[theme]};);
p(});
p(`);
p(unction Toggle({on,onChange,c}:{on:boolean;onChange:()=>void;c:Record<string,string>}){);
p(  return <button onClick={onChange} role="switch" aria-checked={on} style={{width:36,height:20,borderRadius:10,border:"none",background:on?c.accent:c.border,position:"relative",cursor:"pointer",transition:"background .2s",flexShrink:0}}><span style={{position:"absolute",top:2,left:on?18:2,width:16,height:16,borderRadius:"50%",background:"#fff",transition:"left .18s",display:"block",boxShadow:"0 1px 3px rgba(0,0,0,.3)"}}/></button>;);
p(});
p(`);
p(unction StatCard({label,value,sub,accent,c}:{label:string;value:string|number;sub:string;accent:string;c:Record<string,string>}){);
p(  return <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,padding:"22px 24px",borderTop:"3px solid "+accent,display:"flex",flexDirection:"column",gap:6}}><div style={{fontSize:10,fontWeight:700,color:c.textMute,textTransform:"uppercase" as const,letterSpacing:"0.1em"}}>{label}</div><div style={{fontSize:32,fontWeight:800,color:c.text,lineHeight:1}}>{value}</div><div style={{fontSize:12,color:c.textSub}}>{sub}</div></div>;);
p(});
p(`);
p(unction Modal({title,onClose,children,c,wide}:{title:string;onClose:()=>void;children:React.ReactNode;c:Record<string,string>;wide?:boolean}){);
p(  return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000,padding:24,backdropFilter:"blur(4px)"}} onClick={onClose}><div style={{background:c.surface,borderRadius:16,width:"100%",maxWidth:wide?680:500,maxHeight:"85vh",overflow:"auto",boxShadow:"0 32px 80px rgba(0,0,0,.4)",border:"1px solid "+c.border}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"20px 24px",borderBottom:"1px solid "+c.border,position:"sticky",top:0,background:c.surface,zIndex:1}}><div style={{fontSize:16,fontWeight:700,color:c.text}}>{title}</div><button onClick={onClose} style={{background:"none",border:"none",color:c.textSub,cursor:"pointer",display:"flex",padding:4}}><IcoClose/></button></div><div style={{padding:"22px 24px"}}>{children}</div></div></div>;);
p(});
p(`);
p(unction ModalFooter({children}:{children:React.ReactNode}){);
p(  return <div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:22,paddingTop:18,borderTop:"1px solid rgba(128,128,128,0.15)"}}>{children}</div>;);
p(});
p(`);
p(unction Field({label,required,children,c}:{label:string;required?:boolean;children:React.ReactNode;c:Record<string,string>}){);
p(  return <div style={{marginBottom:16}}><label style={{display:"block",fontSize:12,fontWeight:600,color:c.textSub,marginBottom:6}}>{label}{required&&<span style={{color:c.danger,marginLeft:3}}>*</span>}</label>{children}</div>;);
p(});
p(`);
p(unction inp(c:Record<string,string>):React.CSSProperties{);
p(  return {width:"100%",padding:"9px 12px",fontSize:13,color:c.text,background:c.surfaceEl,border:"1px solid "+c.border,borderRadius:8,outline:"none",boxSizing:"border-box" as const,fontFamily:"inherit"};);
p(});
p(`);
p(unction PriBtn({children,disabled,onClick,c,danger}:{children:React.ReactNode;disabled?:boolean;onClick:()=>void;c:Record<string,string>;danger?:boolean}){);
p(  return <button onClick={onClick} disabled={disabled} style={{padding:"9px 20px",borderRadius:8,border:"none",fontSize:13,fontWeight:600,cursor:disabled?"not-allowed":"pointer",background:danger?c.danger:c.accent,color:"#fff",opacity:disabled?0.5:1}}>{children}</button>;);
p(});
p(unction SecBtn({children,onClick,c}:{children:React.ReactNode;onClick:()=>void;c:Record<string,string>}){);
p(  return <button onClick={onClick} style={{padding:"9px 16px",borderRadius:8,border:"1px solid "+c.border,background:"transparent",color:c.textSub,fontSize:13,fontWeight:500,cursor:"pointer"}}>{children}</button>;);
p(});
p(`);
p(unction LogoUploader({current,onUpload,c}:{current?:string;onUpload:(b64:string)=>void;c:Record<string,string>}){);
p(  const ref=React.useRef<HTMLInputElement>(null););
p(  const handle=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>onUpload(r.result as string);r.readAsDataURL(f);};);
p(  return <div onClick={()=>ref.current?.click()} style={{width:"100%",height:100,border:"2px dashed "+c.border,borderRadius:10,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8,cursor:"pointer",background:c.surfaceEl,overflow:"hidden",position:"relative"}}>{current?<><img src={current} alt="logo" style={{maxHeight:80,maxWidth:"90%",objectFit:"contain"}}/><div style={{position:"absolute",bottom:6,right:8,fontSize:10,color:c.textMute}}>click to change</div></>:<><span style={{color:c.textMute}}><IcoUpload/></span><span style={{fontSize:12,color:c.textSub}}>Upload logo (PNG / SVG)</span></>}<input ref={ref} type="file" accept="image/*" style={{display:"none"}} onChange={handle}/></div>;);
p(});
p(`);
p(unction FeatureRow({org,onSave,c}:{org:any;onSave:(f:any)=>Promise<void>;c:Record<string,string>}){);
p(  const [feats,setFeats]=React.useState({...org.features}););
p(  const [saving,setSaving]=React.useState(false););
p(  const [saved,setSaved]=React.useState(false););
p(  const dirty=JSON.stringify(feats)!==JSON.stringify(org.features););
p(  const save=async()=>{setSaving(true);try{await onSave(feats);setSaved(true);setTimeout(()=>setSaved(false),2000);}finally{setSaving(false);}};);
p(  return <tr style={{borderBottom:"1px solid "+c.border}}>);
p(    <td style={{padding:"12px 20px",minWidth:180}}>);
p(      <div style={{display:"flex",alignItems:"center",gap:10}}>);
p(        {org.logoUrl?<img src={org.logoUrl} alt="" style={{width:28,height:28,borderRadius:6,objectFit:"contain",background:c.surfaceEl}}/>:<div style={{width:28,height:28,borderRadius:7,background:c.accentBg,color:c.accent,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:12}}>{org.name?.[0]?.toUpperCase()}</div>});
p(        <div><div style={{fontSize:13,fontWeight:600,color:c.text}}>{org.name}</div><div style={{fontSize:10,color:c.textMute,fontFamily:"monospace"}}>/{org.slug}</div></div>);
p(      </div>);
p(    </td>);
p(    {FEATURES.map(f=><td key={f.key} style={{padding:"12px 10px",textAlign:"center" as const}}><Toggle on={!!feats[f.key]} onChange={()=>setFeats((p:any)=>({...p,[f.key]:!p[f.key]}))} c={c}/></td>)});
p(    <td style={{padding:"12px 14px"}}>);
p(      <button onClick={save} disabled={!dirty||saving} style={{padding:"5px 14px",borderRadius:7,border:"1px solid "+(saved?c.accentDim:dirty?c.accent:c.border),background:saved?c.accentBg:dirty?c.accent:"transparent",color:saved?c.accent:dirty?"#fff":c.textMute,fontSize:12,fontWeight:600,cursor:dirty?"pointer":"default",display:"flex",alignItems:"center",gap:5}}>);
p(        {saved?<><IcoCheck/>Saved</>:saving?"...":"Save"});
p(      </button>);
p(    </td>);
p(  </tr>;);
p(});
p(`);
p(unction ComingSoon({title,desc,icon,c}:{title:string;desc:string;icon:React.ReactNode;c:Record<string,string>}){);
p(  const items=COMING_SOON_ITEMS[title]??[];);
p(  const icons:Record<string,string>={"X1":"??","X2":"??","X3":"??","X4":"??"};);
p(  return <div style={{padding:"32px 36px"}}>);
p(    <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:8}}>);
p(      <div style={{width:40,height:40,borderRadius:10,background:c.surfaceEl,border:"1px solid "+c.border,display:"flex",alignItems:"center",justifyContent:"center",color:c.textSub}}>{icon}</div>);
p(      <div><h1 style={{fontSize:24,fontWeight:800,margin:0}}>{title}</h1><p style={{fontSize:13,color:c.textSub,margin:0}}>{desc}</p></div>);
p(    </div>);
p(    <div style={{marginTop:32,display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:16}}>);
p(      {items.map((item:any)=>();
p(        <div key={item.label} style={{background:c.surface,border:"1px solid "+c.border,borderRadius:12,padding:"20px 22px"}}>);
p(          <div style={{fontSize:20,marginBottom:8}}>{icons[item.icon]??item.icon}</div>);
p(          <div style={{fontSize:14,fontWeight:700,color:c.text,marginBottom:4}}>{item.label}</div>);
p(          <div style={{fontSize:12,color:c.textSub,lineHeight:1.6}}>{item.detail}</div>);
p(          <div style={{marginTop:12,display:"inline-block",padding:"3px 10px",borderRadius:20,background:c.surfaceEl,border:"1px solid "+c.border,fontSize:11,color:c.textMute,fontWeight:600}}>Coming soon</div>);
p(        </div>);
p(      ))});
p(    </div>);
p(  </div>;);
p(});
p(`);
p(export function SuperAdminPage(){);
p(  const {user}=useUser(););
p(  const savedPlans=useQuery(api.superadmin.listPlanDefinitions););
p(  const upsertPlan=useMutation(api.superadmin.upsertPlanDefinition););
p(  const deletePlanDef=useMutation(api.superadmin.deletePlanDefinition););
p(  const {signOut}=useClerk(););
p(  const {theme,toggle,c}=useTheme(););
p(`);
p(  const [tab,setTab]=React.useState<Tab>("overview"););
p(  const [search,setSearch]=React.useState(""););
p(  const [planFilter,setPlanFilter]=React.useState<"ALL"|Plan>("ALL"););
p(  const [statusFilter,setStatusFilter]=React.useState<"ALL"|OrgStatus>("ALL"););
p(  const [createOpen,setCreateOpen]=React.useState(false););
p(  const [editOrg,setEditOrg]=React.useState<any>(null););
p(  const [blockModal,setBlockModal]=React.useState<any>(null););
p(  const [deleteConfirm,setDeleteConfirm]=React.useState<any>(null););
p(  const [blockReason,setBlockReason]=React.useState(""););
p(  const [submitting,setSubmitting]=React.useState(false););
p(  const [planDefs,setPlanDefs]=React.useState(DEFAULT_PLANS););
p(  const [planEditIdx,setPlanEditIdx]=React.useState<number|null>(null););
p(  const [planEditVal,setPlanEditVal]=React.useState<any>(null););
p(`);
p(  React.useEffect(()=>{);
p(    if(savedPlans&&savedPlans.length>0){);
p(      setPlanDefs(savedPlans.map((p:any)=>({);
p(        id:p.planId,name:p.name,desc:p.desc??"",price:p.price,);
p(        annualPrice:p.annualPrice,maxUsers:p.maxUsers,maxLocations:p.maxLocations,);
p(        color:p.color??"#22c55e",);
p(        features:p.features??DEFAULT_FEATURES_BY_PLAN[p.planId]??DEFAULT_FEATURES_BY_PLAN.free,);
p(      }))););
p(    });
p(  },[savedPlans]););
p(`);
p(  const emptyForm={admins:[] as {name:string;email:string}[],name:"",slug:"",ownerEmail:"",ownerName:"",ownerPhone:"",plan:"free" as Plan,adminNotes:"",logoUrl:"",address:"",website:"",taxId:"",maxUsers:"",maxLocations:"",features:{} as Record<string,boolean>};);
p(  const [form,setForm]=React.useState(emptyForm););
p(  const [editForm,setEditForm]=React.useState<any>({}););
p(`);
p(  const orgs=useQuery(api.superadmin.listOrgs););
p(  const stats=useQuery(api.superadmin.platformStats););
p(  const audit=useQuery(api.superadmin.listAuditLog,{limit:100}););
p(`);
p(  const createOrg=useMutation(api.superadmin.createOrg););
p(  const sendAdminInvites=useAction(api.superadmin.sendAdminInvites););
p(  const updateOrg=useMutation(api.superadmin.updateOrg););
p(  const blockOrg=useMutation(api.superadmin.blockOrg););
p(  const unblockOrg=useMutation(api.superadmin.unblockOrg););
p(  const updatePlan=useMutation(api.superadmin.updatePlan););
p(  const updateFeatures=useMutation(api.superadmin.updateFeatures););
p(  const deleteOrg=useMutation(api.superadmin.deleteOrg););
p(`);
p(  const actor={actorClerkId:user?.id??"",actorName:user?.fullName??"Superadmin"};);
p(`);
p(  const filtered=orgs?.filter((o:any)=>{);
p(    const q=search.toLowerCase(););
p(    const ok=!q||o.name.toLowerCase().includes(q)||(o.ownerEmail??"").toLowerCase().includes(q)||(o.slug??"").toLowerCase().includes(q););
p(    return ok&&(planFilter==="ALL"||o.plan===planFilter)&&(statusFilter==="ALL"||o.status===statusFilter););
p(  }););
p(`);
p(  const handleCreate=async()=>{if(!form.name||!form.slug||!form.ownerEmail)return;setSubmitting(true);try{await createOrg({...form,...actor});setCreateOpen(false);setForm(emptyForm);}finally{setSubmitting(false);}};);
p(  const handleEdit=async()=>{if(!editOrg)return;setSubmitting(true);try{await updateOrg({orgId:editOrg._id,...editForm,...actor});setEditOrg(null);}finally{setSubmitting(false);}};);
p(  const handleBlockToggle=async()=>{if(!blockModal)return;setSubmitting(true);try{blockModal.status==="blocked"?await unblockOrg({orgId:blockModal._id,...actor}):await blockOrg({orgId:blockModal._id,reason:blockReason||undefined,...actor});setBlockModal(null);setBlockReason("");}finally{setSubmitting(false);}};);
p(  const handleDelete=async()=>{if(!deleteConfirm)return;setSubmitting(true);try{await deleteOrg({orgId:deleteConfirm._id,...actor});setDeleteConfirm(null);}finally{setSubmitting(false);}};);
p(`);
p(  const savePlanEdit=()=>{);
p(    const pd=planEditVal as any;);
p(    const feats={checkInEnabled:pd.features?.checkInEnabled??false,badgesEnabled:pd.features?.badgesEnabled??false,schedulingEnabled:pd.features?.schedulingEnabled??false,messagingEnabled:pd.features?.messagingEnabled??false,analyticsEnabled:pd.features?.analyticsEnabled??false,notificationsEnabled:pd.features?.notificationsEnabled??false,attendanceEnabled:pd.features?.attendanceEnabled??false,multiLocationEnabled:pd.features?.multiLocationEnabled??false,apiAccessEnabled:pd.features?.apiAccessEnabled??false,ssoEnabled:pd.features?.ssoEnabled??false,whitelabelEnabled:pd.features?.whitelabelEnabled??false,dedicatedSupportEnabled:pd.features?.dedicatedSupportEnabled??false};);
p(    if(planEditIdx!<planDefs.length){setPlanDefs(d=>d.map((p,i)=>i===planEditIdx?{...pd,features:feats}:p));}else{setPlanDefs(d=>[...d,{...pd,features:feats}]);});
p(    upsertPlan({planId:(pd.id??pd.name??"plan").toLowerCase().replace(/\s+/g,"-"),name:pd.name??"",desc:pd.desc??"",price:Number(pd.price)||0,annualPrice:Number(pd.annualPrice)||0,maxUsers:Number(pd.maxUsers)||0,maxLocations:Number(pd.maxLocations)||0,color:pd.color??"#22c55e",features:feats,...actor}).catch(console.error););
p(    setPlanEditIdx(null);setPlanEditVal(null););
p(  };);
p(`);
p(  const NAV:{id:Tab;label:string;Icon:()=>React.ReactElement;group:string}[]=[);
p(    {id:"overview",      label:"Overview",        Icon:IcoGrid,      group:"Platform"},);
p(    {id:"accounts",      label:"Accounts",        Icon:IcoUsers,     group:"Platform"},);
p(    {id:"plans",         label:"Plans & Pricing", Icon:IcoDollar,    group:"Platform"},);
p(    {id:"features",      label:"Feature flags",   Icon:IcoSliders,   group:"Platform"},);
p(    {id:"notifications", label:"Notifications",   Icon:IcoBell,      group:"Ops"},);
p(    {id:"billing",       label:"Billing",         Icon:IcoCreditCard,group:"Ops"},);
p(    {id:"integrations",  label:"Integrations",    Icon:IcoZap,       group:"Ops"},);
p(    {id:"tickets",       label:"Support Tickets", Icon:IcoTicket,    group:"Ops"},);
p(    {id:"templates",     label:"Templates",       Icon:IcoLayout,    group:"Ops"},);
p(    {id:"health",        label:"System Health",   Icon:IcoActivity,  group:"Ops"},);
p(    {id:"audit",         label:"Audit log",       Icon:IcoLog,       group:"System"},);
p(    {id:"settings",      label:"Settings",        Icon:IcoGear,      group:"System"},);
p(  ];);
p(`);
p(  const th:React.CSSProperties={padding:"11px 14px",textAlign:"left" as const,fontSize:10,fontWeight:700,color:c.textMute,textTransform:"uppercase" as const,letterSpacing:"0.08em",background:c.surfaceEl,whiteSpace:"nowrap" as const};);
p(  const planColor:Record<string,string>={free:c.textSub,pro:c.accent,enterprise:c.warn,custom:c.purple};);
p(  const statusDot:Record<string,string>={active:c.accent,trial:c.info,blocked:c.danger,suspended:c.warn};);
p(  const groups=["Platform","Ops","System"];);
p(`);
p(  return();
p(    <div style={{display:"flex",height:"100vh",fontFamily:"'Inter',system-ui,sans-serif",background:c.bg,color:c.text}}>);
p(`);
p(      <aside style={{width:232,flexShrink:0,background:c.surface,borderRight:"1px solid "+c.border,display:"flex",flexDirection:"column",height:"100vh",position:"sticky",top:0}}>);
p(        <div style={{padding:"20px 18px 16px",borderBottom:"1px solid "+c.border,display:"flex",alignItems:"center",justifyContent:"space-between"}}>);
p(          <div style={{display:"flex",alignItems:"center",gap:10}}>);
p(            <div style={{width:36,height:36,borderRadius:10,background:c.accent,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:18,color:"#fff"}}>P</div>);
p(            <div><div style={{fontWeight:800,fontSize:16,color:c.text}}>Porta</div><div style={{fontSize:9,fontWeight:700,letterSpacing:"0.12em",color:c.accent,textTransform:"uppercase" as const}}>Superadmin</div></div>);
p(          </div>);
p(          <button onClick={toggle} style={{background:"none",border:"1px solid "+c.border,borderRadius:8,padding:"6px 7px",color:c.textSub,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>{theme==="dark"?<IcoSun/>:<IcoMoon/>}</button>);
p(        </div>);
p(        <nav style={{padding:"10px",flex:1,overflowY:"auto"}}>);
p(          {groups.map(grp=>();
p(            <div key={grp}>);
p(              <div style={{fontSize:9,fontWeight:700,color:c.textMute,textTransform:"uppercase" as const,letterSpacing:"0.1em",padding:"10px 10px 6px"}}>{grp}</div>);
p(              {NAV.filter(n=>n.group===grp).map(n=>();
p(                <button key={n.id} onClick={()=>setTab(n.id)} style={{display:"flex",alignItems:"center",gap:10,width:"100%",padding:"9px 12px",borderRadius:8,border:"none",background:tab===n.id?c.accentBg:"transparent",color:tab===n.id?c.accent:c.textSub,fontSize:13,fontWeight:tab===n.id?600:400,cursor:"pointer",textAlign:"left" as const,transition:"all .15s",marginBottom:2}}>);
p(                  <n.Icon/>);
p(                  <span style={{flex:1}}>{n.label}</span>);
p(                  {n.id==="accounts"&&orgs&&<span style={{background:c.surfaceEl,color:c.textSub,borderRadius:20,fontSize:10,fontWeight:700,padding:"1px 7px"}}>{orgs.length}</span>});
p(                  {["notifications","billing","integrations","tickets","templates","health"].includes(n.id)&&<span style={{background:c.surfaceEl,color:c.textMute,borderRadius:20,fontSize:9,fontWeight:700,padding:"1px 6px"}}>Soon</span>});
p(                </button>);
p(              ))});
p(            </div>);
p(          ))});
p(        </nav>);
p(        <div style={{padding:"14px 16px",borderTop:"1px solid "+c.border}}>);
p(          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}>);
p(            <div style={{width:32,height:32,borderRadius:"50%",background:c.accentBg,color:c.accent,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:13,flexShrink:0}}>{user?.firstName?.[0]??"S"}</div>);
p(            <div style={{minWidth:0}}><div style={{fontSize:13,fontWeight:600,color:c.text,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{user?.fullName}</div><div style={{fontSize:11,color:c.textMute}}>Superadmin</div></div>);
p(          </div>);
p(          <button onClick={()=>signOut()} style={{display:"flex",alignItems:"center",gap:8,width:"100%",padding:"8px 10px",borderRadius:7,border:"1px solid "+c.border,background:"transparent",color:c.textSub,fontSize:12,fontWeight:500,cursor:"pointer"}}><IcoLogout/>Sign out</button>);
p(        </div>);
p(      </aside>);
p(`);
p(      <main style={{flex:1,overflow:"auto",minWidth:0}}>);
p(`);
p(        {tab==="overview"&&();
p(          <div style={{padding:"32px 36px"}}>);
p(            <h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Platform overview</h1>);
p(            <p style={{fontSize:13,color:c.textSub,marginBottom:28}}>Live metrics across all Porta organisations</p>);
p(            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:14}}>);
p(              <StatCard label="Total orgs"     value={stats?.totalOrgs??"?"}     sub="all time"         accent="#6366f1" c={c}/>);
p(              <StatCard label="Active"         value={stats?.activeOrgs??"?"}    sub="currently live"   accent={c.accent} c={c}/>);
p(              <StatCard label="On trial"       value={stats?.trialOrgs??"?"}     sub="14-day window"    accent={c.info} c={c}/>);
p(              <StatCard label="Blocked"        value={stats?.blockedOrgs??"?"}   sub="access suspended" accent={c.danger} c={c}/>);
p(            </div>);
p(            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:28}}>);
p(              <StatCard label="Pro accounts"   value={stats?.proOrgs??"?"}       sub="paid plan"        accent={c.accent} c={c}/>);
p(              <StatCard label="Enterprise"     value={stats?.enterpriseOrgs??"?"}sub="enterprise plan"  accent={c.warn} c={c}/>);
p(              <StatCard label="Total visitors" value={stats?.totalVisitors??"?"} sub="all-time check-ins" accent={c.purple} c={c}/>);
p(              <StatCard label="Visitors (7d)"  value={stats?.weekVisitors??"?"}  sub="this week"        accent="#fb7185" c={c}/>);
p(            </div>);
p(            <div style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:18,marginBottom:20}}>);
p(              <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,padding:"22px 24px"}}>);
p(                <div style={{fontSize:13,fontWeight:700,marginBottom:20,color:c.text}}>Accounts by plan</div>);
p(                {stats&&[{label:"Free",count:stats.byPlan?.free??0,color:c.textSub},{label:"Pro",count:stats.byPlan?.pro??0,color:c.accent},{label:"Enterprise",count:stats.byPlan?.enterprise??0,color:c.warn},{label:"Custom",count:stats.byPlan?.custom??0,color:c.purple}].map(({label,count,color})=>{);
p(                  const pct=(stats.totalOrgs||0)===0?0:Math.round((count/stats.totalOrgs)*100););
p(                  return <div key={label} style={{marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:6}}><span style={{fontWeight:600,color}}>{label}</span><span style={{color:c.textMute}}>{count} ? {pct}%</span></div><div style={{height:6,background:c.border,borderRadius:3,overflow:"hidden"}}><div style={{width:pct+"%",height:"100%",background:color,borderRadius:3}}/></div></div>;);
p(                })});
p(              </div>);
p(              <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,padding:"22px 24px"}}>);
p(                <div style={{fontSize:13,fontWeight:700,marginBottom:4,color:c.text}}>Visitor check-ins - last 14 days</div>);
p(                <div style={{fontSize:12,color:c.textSub,marginBottom:18}}>Across all organisations</div>);
p(                {stats&&<div style={{display:"flex",alignItems:"flex-end",gap:5,height:130}}>{(stats.dailyVisitors||[]).map((d:any,i:number)=>{const max=Math.max(...(stats.dailyVisitors||[]).map((x:any)=>x.count),1);const h=Math.max((d.count/max)*100,d.count>0?6:2);return <div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",height:"100%",gap:4}}><div title={d.count+" visitors"} style={{width:"100%",height:h+"%",background:c.accent,borderRadius:"3px 3px 0 0",opacity:0.8}}/>{i%2===0&&<span style={{fontSize:9,color:c.textMute,whiteSpace:"nowrap"}}>{d.label}</span>}</div>;})}</div>});
p(              </div>);
p(            </div>);
p(            {audit&&audit.length>0&&<div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,overflow:"hidden"}}>);
p(              <div style={{padding:"15px 22px",borderBottom:"1px solid "+c.border,display:"flex",justifyContent:"space-between",alignItems:"center"}}>);
p(                <div style={{fontSize:13,fontWeight:700,color:c.text}}>Recent activity</div>);
p(                <button onClick={()=>setTab("audit")} style={{fontSize:12,color:c.accent,background:"none",border:"none",cursor:"pointer",fontWeight:600,display:"flex",alignItems:"center",gap:4}}>View all <IcoChevR/></button>);
p(              </div>);
p(              {audit.slice(0,6).map((a:any)=><div key={a._id} style={{display:"flex",alignItems:"center",gap:14,padding:"11px 22px",borderBottom:"1px solid "+c.surfaceEl}}><span style={{background:c.accentBg,color:c.accent,fontSize:10,fontWeight:700,padding:"2px 8px",borderRadius:6,fontFamily:"monospace",flexShrink:0}}>{a.action}</span><span style={{fontSize:13,color:c.text,flex:1}}>{a.targetLabel||a.targetId||"?"}</span><span style={{fontSize:12,color:c.textSub,flexShrink:0}}>{a.actorName}</span><span style={{fontSize:11,color:c.textMute,flexShrink:0,fontFamily:"monospace"}}>{new Date(a.createdAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div>)});
p(            </div>});
p(          </div>);
p(        )});
p(`);
p(        {tab==="accounts"&&();
p(          <div style={{padding:"32px 36px"}}>);
p(            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}>);
p(              <div><h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Accounts</h1><p style={{fontSize:13,color:c.textSub}}>{orgs?.length??0} organisations on Porta</p></div>);
p(              <button onClick={()=>setCreateOpen(true)} style={{display:"flex",alignItems:"center",gap:7,padding:"9px 18px",background:c.accent,color:"#fff",border:"none",borderRadius:8,fontSize:13,fontWeight:600,cursor:"pointer"}}><IcoPlus/>New account</button>);
p(            </div>);
p(            <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:20}}>);
p(              <div style={{display:"flex",alignItems:"center",gap:8,background:c.surface,border:"1px solid "+c.border,borderRadius:8,padding:"8px 12px",width:280}}>);
p(                <span style={{color:c.textMute}}><IcoSearch/></span>);
p(                <input placeholder="Search name, email, slug..." value={search} onChange={e=>setSearch(e.target.value)} style={{border:"none",outline:"none",background:"none",fontSize:13,color:c.text,width:"100%"}}/>);
p(                {search&&<button onClick={()=>setSearch("")} style={{background:"none",border:"none",color:c.textMute,cursor:"pointer",display:"flex"}}><IcoClose/></button>});
p(              </div>);
p(              <div style={{display:"flex",gap:4}}>{(["ALL","free","pro","enterprise","custom"] as const).map(pp=>(<button key={pp} onClick={()=>setPlanFilter(pp)} style={{padding:"7px 14px",borderRadius:20,border:"1px solid "+(planFilter===pp?c.accent:c.border),background:planFilter===pp?c.accentBg:"transparent",color:planFilter===pp?c.accent:c.textSub,fontSize:12,fontWeight:500,cursor:"pointer",textTransform:"capitalize" as const}}>{pp==="ALL"?"All plans":pp}</button>))}</div>);
p(              <div style={{display:"flex",gap:4}}>{(["ALL","active","trial","blocked","suspended"] as const).map(ss=>(<button key={ss} onClick={()=>setStatusFilter(ss)} style={{padding:"7px 14px",borderRadius:20,border:"1px solid "+(statusFilter===ss?c.purple:c.border),background:statusFilter===ss?c.purpleBg:"transparent",color:statusFilter===ss?c.purple:c.textSub,fontSize:12,fontWeight:500,cursor:"pointer",textTransform:"capitalize" as const}}>{ss==="ALL"?"All status":ss}</button>))}</div>);
p(            </div>);
p(            <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,overflow:"hidden"}}>);
p(              <table style={{width:"100%",borderCollapse:"collapse"}}>);
p(                <thead><tr style={{borderBottom:"1px solid "+c.border}}>{["Organisation","Plan","Status","Owner","Users","Created","Actions"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead>);
p(                <tbody>);
p(                  {orgs===undefined?<tr><td colSpan={7} style={{padding:40,textAlign:"center",color:c.textMute}}>Loading...</td></tr>);
p(                  :filtered?.length===0?<tr><td colSpan={7} style={{padding:40,textAlign:"center",color:c.textMute}}>No accounts match your filters.</td></tr>);
p(                  :filtered?.map((o:any)=>();
p(                    <tr key={o._id} style={{borderBottom:"1px solid "+c.border}}>);
p(                      <td style={{padding:"13px 14px"}}>);
p(                        <div style={{display:"flex",alignItems:"center",gap:10}}>);
p(                          {o.logoUrl?<img src={o.logoUrl} alt="" style={{width:34,height:34,borderRadius:8,objectFit:"contain",background:c.surfaceEl,border:"1px solid "+c.border}}/>:<div style={{width:34,height:34,borderRadius:9,background:c.accentBg,color:c.accent,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:14,flexShrink:0}}>{o.name?.[0]?.toUpperCase()}</div>});
p(                          <div><div style={{fontSize:13,fontWeight:600,color:c.text}}>{o.name}</div><div style={{fontSize:10,color:c.textMute,fontFamily:"monospace"}}>/{o.slug}</div>{o.website&&<div style={{fontSize:10,color:c.info}}>{o.website}</div>}</div>);
p(                        </div>);
p(                      </td>);
p(                      <td style={{padding:"13px 14px"}}><select value={o.plan} onChange={e=>updatePlan({orgId:o._id,plan:e.target.value as Plan,...actor})} style={{padding:"4px 10px",borderRadius:20,border:"1px solid "+c.border,background:c.surfaceEl,color:planColor[o.plan]||c.textSub,fontSize:12,fontWeight:700,cursor:"pointer",outline:"none"}}>{planDefs.map(pp=><option key={pp.id} value={pp.id}>{pp.name}</option>)}</select></td>);
p(                      <td style={{padding:"13px 14px"}}><span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"4px 10px",borderRadius:20,background:c.surfaceEl,color:statusDot[o.status]||c.textSub,fontSize:11,fontWeight:700,textTransform:"capitalize" as const}}><span style={{width:6,height:6,borderRadius:"50%",background:statusDot[o.status]||c.textMute}}/>{o.status||"active"}</span></td>);
p(                      <td style={{padding:"13px 14px"}}><div style={{fontSize:13,fontWeight:500,color:c.text}}>{o.ownerName||"?"}</div><div style={{fontSize:11,color:c.textMute}}>{o.ownerEmail}</div>{o.ownerPhone&&<div style={{fontSize:11,color:c.textMute}}>{o.ownerPhone}</div>}</td>);
p(                      <td style={{padding:"13px 14px",fontSize:13,color:c.textSub}}>{o.maxUsers||"?"}</td>);
p(                      <td style={{padding:"13px 14px",fontSize:11,color:c.textMute,fontFamily:"monospace"}}>{new Date(o.createdAt).toLocaleDateString([],{month:"short",day:"numeric",year:"numeric"})}</td>);
p(                      <td style={{padding:"13px 14px"}}>);
p(                        <div style={{display:"flex",gap:5}}>);
p(                          <button onClick={()=>{setEditOrg(o);setEditForm({name:o.name,slug:o.slug,ownerEmail:o.ownerEmail,ownerName:o.ownerName||"",ownerPhone:o.ownerPhone||"",adminNotes:o.adminNotes||"",logoUrl:o.logoUrl||"",address:o.address||"",website:o.website||"",taxId:o.taxId||"",maxUsers:o.maxUsers||"",maxLocations:o.maxLocations||""});}} style={{padding:"5px 10px",borderRadius:6,border:"1px solid "+c.border,background:"transparent",color:c.textSub,fontSize:12,fontWeight:500,cursor:"pointer",display:"flex",alignItems:"center",gap:4}}><IcoEdit/>Edit</button>);
p(                          <button onClick={()=>setBlockModal(o)} style={{padding:"5px 10px",borderRadius:6,border:"1px solid "+(o.status==="blocked"?c.accentDim:c.border),background:o.status==="blocked"?c.accentBg:"transparent",color:o.status==="blocked"?c.accent:c.danger,fontSize:12,fontWeight:500,cursor:"pointer"}}>{o.status==="blocked"?"Unblock":"Block"}</button>);
p(                          <button onClick={()=>setDeleteConfirm(o)} style={{padding:"5px 8px",borderRadius:6,border:"1px solid "+c.border,background:"transparent",color:c.textMute,cursor:"pointer",display:"flex",alignItems:"center"}}><IcoTrash/></button>);
p(                        </div>);
p(                      </td>);
p(                    </tr>);
p(                  ))});
p(                </tbody>);
p(              </table>);
p(            </div>);
p(          </div>);
p(        )});
p(`);
p(        {tab==="plans"&&();
p(          <div style={{padding:"32px 36px"}}>);
p(            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}>);
p(              <div><h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Plans & Pricing</h1><p style={{fontSize:13,color:c.textSub}}>Define tiers, pricing, limits and which features each plan unlocks</p></div>);
p(              <button onClick={()=>{setPlanEditIdx(planDefs.length);setPlanEditVal({id:"plan-"+Date.now(),name:"",price:0,annualPrice:0,maxUsers:10,maxLocations:1,color:c.accent,desc:"",features:{...DEFAULT_FEATURES_BY_PLAN.free}});}} style={{display:"flex",alignItems:"center",gap:7,padding:"9px 18px",background:c.accent,color:"#fff",border:"none",borderRadius:8,fontSize:13,fontWeight:600,cursor:"pointer"}}><IcoPlus/>New plan</button>);
p(            </div>);
p(            <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:16,marginBottom:32}}>);
p(              {planDefs.map((plan,idx)=>();
p(                <div key={plan.id} style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,overflow:"hidden"}}>);
p(                  <div style={{height:4,background:plan.color}}/>);
p(                  <div style={{padding:"20px 22px"}}>);
p(                    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}>);
p(                      <div style={{fontSize:18,fontWeight:800,color:plan.color}}>{plan.name}</div>);
p(                      <button onClick={()=>{setPlanEditIdx(idx);setPlanEditVal({...plan,features:{...plan.features}});}} style={{background:c.surfaceEl,border:"1px solid "+c.border,borderRadius:6,padding:"4px 8px",color:c.textSub,cursor:"pointer",display:"flex",alignItems:"center",gap:4,fontSize:12}}><IcoEdit/>Edit</button>);
p(                    </div>);
p(                    <div style={{fontSize:12,color:c.textSub,marginBottom:14}}>{plan.desc}</div>);
p(                    <div style={{display:"flex",gap:16,marginBottom:14}}>);
p(                      <div><div style={{fontSize:9,color:c.textMute,fontWeight:700,textTransform:"uppercase" as const,letterSpacing:"0.08em"}}>Monthly</div><div style={{fontSize:22,fontWeight:800,color:c.text}}>{plan.price===0?"Free":"$"+plan.price}</div></div>);
p(                      {plan.annualPrice>0&&<div><div style={{fontSize:9,color:c.textMute,fontWeight:700,textTransform:"uppercase" as const,letterSpacing:"0.08em"}}>Annual</div><div style={{fontSize:22,fontWeight:800,color:c.accent}}>{"$"+plan.annualPrice}<span style={{fontSize:11,fontWeight:400,color:c.textMute}}>/mo</span></div></div>});
p(                    </div>);
p(                    <div style={{display:"flex",gap:8,marginBottom:14}}>);
p(                      <div style={{flex:1,background:c.surfaceEl,borderRadius:8,padding:"8px 10px"}}><div style={{fontSize:9,color:c.textMute,fontWeight:700}}>MAX USERS</div><div style={{fontSize:16,fontWeight:700,color:c.text}}>{plan.maxUsers>=999?"inf":plan.maxUsers}</div></div>);
p(                      <div style={{flex:1,background:c.surfaceEl,borderRadius:8,padding:"8px 10px"}}><div style={{fontSize:9,color:c.textMute,fontWeight:700}}>LOCATIONS</div><div style={{fontSize:16,fontWeight:700,color:c.text}}>{plan.maxLocations>=99?"inf":plan.maxLocations}</div></div>);
p(                    </div>);
p(                    <div style={{display:"flex",flexDirection:"column",gap:3}}>);
p(                      {FEATURES.filter(f=>(plan.features as any)?.[f.key]).map(f=><div key={f.key} style={{display:"flex",alignItems:"center",gap:6,fontSize:11,color:c.textSub}}><span style={{color:c.accent,fontWeight:700}}>+</span>{f.label}</div>)});
p(                    </div>);
p(                  </div>);
p(                </div>);
p(              ))});
p(            </div>);
p(            <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,padding:"22px 24px"}}>);
p(              <div style={{fontSize:14,fontWeight:700,marginBottom:16,color:c.text,display:"flex",alignItems:"center",gap:8}}><IcoShield/>Feature permissions matrix</div>);
p(              <div style={{overflowX:"auto"}}>);
p(                <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}>);
p(                  <thead><tr><th style={{...th,textAlign:"left" as const}}>Feature</th>{planDefs.map(pp=><th key={pp.id} style={{...th,textAlign:"center" as const,color:pp.color}}>{pp.name}</th>)}</tr></thead>);
p(                  <tbody>);
p(                    {FEATURES.map(f=>();
p(                      <tr key={f.key} style={{borderBottom:"1px solid "+c.border}}>);
p(                        <td style={{padding:"10px 14px",color:c.textSub}}>{f.label}<div style={{fontSize:10,color:c.textMute}}>{f.desc}</div></td>);
p(                        {planDefs.map(pp=><td key={pp.id} style={{padding:"10px 14px",textAlign:"center" as const}}>{(pp.features as any)?.[f.key]?<span style={{color:c.accent,fontWeight:700}}>+</span>:<span style={{color:c.border}}>-</span>}</td>)});
p(                      </tr>);
p(                    ))});
p(                  </tbody>);
p(                </table>);
p(              </div>);
p(            </div>);
p(          </div>);
p(        )});
p(`);
p(        {tab==="features"&&();
p(          <div style={{padding:"32px 36px"}}>);
p(            <h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Feature flags</h1>);
p(            <p style={{fontSize:13,color:c.textSub,marginBottom:24}}>Override features per organisation. Changes apply instantly.</p>);
p(            <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,overflow:"auto"}}>);
p(              <table style={{width:"100%",borderCollapse:"collapse",whiteSpace:"nowrap"}}>);
p(                <thead><tr style={{borderBottom:"1px solid "+c.border}}>);
p(                  <th style={{...th,minWidth:200,textAlign:"left" as const}}>Organisation</th>);
p(                  {FEATURES.map(f=><th key={f.key} title={f.desc} style={{...th,textAlign:"center" as const}}>{f.label}</th>)});
p(                  <th style={{padding:"11px 14px",background:c.surfaceEl}}/>);
p(                </tr></thead>);
p(                <tbody>);
p(                  {orgs===undefined?<tr><td colSpan={FEATURES.length+2} style={{padding:32,textAlign:"center",color:c.textMute}}>Loading...</td></tr>);
p(                  :orgs.map((o:any)=><FeatureRow key={o._id} org={o} c={c} onSave={async f=>{await updateFeatures({orgId:o._id,features:f,...actor});}}/>)});
p(                </tbody>);
p(              </table>);
p(            </div>);
p(          </div>);
p(        )});
p(`);
p(        {tab==="notifications"&&<ComingSoon title="Notifications" desc="Manage platform-wide notification channels and templates" icon={<IcoBell/>} c={c}/>});
p(        {tab==="billing"&&<ComingSoon title="Billing" desc="Stripe integration, invoices and revenue analytics" icon={<IcoCreditCard/>} c={c}/>});
p(        {tab==="integrations"&&<ComingSoon title="Integrations" desc="Connect Porta to third-party tools and services" icon={<IcoZap/>} c={c}/>});
p(        {tab==="tickets"&&<ComingSoon title="Support Tickets" desc="Triage and respond to support requests from org admins" icon={<IcoTicket/>} c={c}/>});
p(        {tab==="templates"&&<ComingSoon title="Templates" desc="Reusable email, badge and check-in form templates" icon={<IcoLayout/>} c={c}/>});
p(        {tab==="health"&&<ComingSoon title="System Health" desc="Live service status, performance and error tracking" icon={<IcoActivity/>} c={c}/>});
p(`);
p(        {tab==="audit"&&();
p(          <div style={{padding:"32px 36px"}}>);
p(            <h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Audit log</h1>);
p(            <p style={{fontSize:13,color:c.textSub,marginBottom:24}}>Every superadmin action, newest first</p>);
p(            <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:14,overflow:"hidden"}}>);
p(              <table style={{width:"100%",borderCollapse:"collapse"}}>);
p(                <thead><tr style={{borderBottom:"1px solid "+c.border}}>{["Action","Target","Detail","By","When"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead>);
p(                <tbody>);
p(                  {audit===undefined?<tr><td colSpan={5} style={{padding:32,textAlign:"center",color:c.textMute}}>Loading...</td></tr>);
p(                  :audit.length===0?<tr><td colSpan={5} style={{padding:32,textAlign:"center",color:c.textMute}}>No actions yet.</td></tr>);
p(                  :audit.map((a:any)=>();
p(                    <tr key={a._id} style={{borderBottom:"1px solid "+c.border}}>);
p(                      <td style={{padding:"12px 14px"}}><span style={{background:c.accentBg,color:c.accent,fontSize:10,fontWeight:700,padding:"3px 8px",borderRadius:6,fontFamily:"monospace"}}>{a.action}</span></td>);
p(                      <td style={{padding:"12px 14px",fontSize:13,fontWeight:500,color:c.text}}>{a.targetLabel||a.targetId||"?"}</td>);
p(                      <td style={{padding:"12px 14px",fontSize:12,color:c.textSub,maxWidth:240}}>{a.detail||"?"}</td>);
p(                      <td style={{padding:"12px 14px",fontSize:13,color:c.text}}>{a.actorName}</td>);
p(                      <td style={{padding:"12px 14px",fontSize:11,color:c.textMute,fontFamily:"monospace",whiteSpace:"nowrap"}}>{new Date(a.createdAt).toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</td>);
p(                    </tr>);
p(                  ))});
p(                </tbody>);
p(              </table>);
p(            </div>);
p(          </div>);
p(        )});
p(`);
p(        {tab==="settings"&&();
p(          <div style={{padding:"32px 36px",maxWidth:700}}>);
p(            <h1 style={{fontSize:24,fontWeight:800,marginBottom:4}}>Settings</h1>);
p(            <p style={{fontSize:13,color:c.textSub,marginBottom:28}}>Global platform configuration</p>);
p(            {[);
p(              {group:"Onboarding",items:[{title:"Trial period length",desc:"Days new accounts get before needing paid plan",value:"14 days"},{title:"Self-serve signups",desc:"Allow orgs to sign up without superadmin approval",value:"Enabled"},{title:"Default plan",desc:"Plan assigned to new organisations on signup",value:"Free"}]},);
p(              {group:"Security & Access",items:[{title:"Require email verification",desc:"Users must verify email before accessing",value:"On"},{title:"API key access",desc:"Allow Pro+ orgs to generate REST API keys",value:"Pro+"},{title:"SSO enforcement",desc:"Require SSO for Enterprise accounts",value:"Optional"}]},);
p(              {group:"Billing",items:[{title:"Default currency",desc:"Currency for all plan pricing and invoices",value:"USD"},{title:"Annual discount",desc:"Discount applied for annual billing",value:"20%"},{title:"Grace period",desc:"Days before blocking after failed payment",value:"7 days"}]},);
p(            ].map(section=>();
p(              <div key={section.group}>);
p(                <div style={{fontSize:11,fontWeight:700,color:c.textMute,textTransform:"uppercase" as const,letterSpacing:"0.1em",marginBottom:10,marginTop:22}}>{section.group}</div>);
p(                <div style={{background:c.surface,border:"1px solid "+c.border,borderRadius:12,overflow:"hidden",marginBottom:4}}>);
p(                  {section.items.map((item,i,arr)=>();
p(                    <div key={item.title} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"15px 20px",borderBottom:i<arr.length-1?"1px solid "+c.border:"none"}}>);
p(                      <div><div style={{fontSize:14,fontWeight:600,color:c.text}}>{item.title}</div><div style={{fontSize:12,color:c.textSub,marginTop:2}}>{item.desc}</div></div>);
p(                      <div style={{fontSize:13,fontWeight:600,color:c.accent,background:c.accentBg,padding:"4px 14px",borderRadius:20,flexShrink:0,marginLeft:16}}>{item.value}</div>);
p(                    </div>);
p(                  ))});
p(                </div>);
p(              </div>);
p(            ))});
p(            <div style={{marginTop:24,background:c.dangerBg,border:"1px solid rgba(239,68,68,0.2)",borderRadius:12,padding:"20px 22px"}}>);
p(              <div style={{fontSize:14,fontWeight:700,color:c.danger,marginBottom:4}}>Danger zone</div>);
p(              <div style={{fontSize:13,color:c.textSub,marginBottom:16}}>These actions are irreversible and affect the entire platform.</div>);
p(              <div style={{display:"flex",gap:10,flexWrap:"wrap" as const}}>);
p(                <button style={{padding:"8px 16px",background:"transparent",border:"1px solid "+c.danger,borderRadius:8,color:c.danger,fontSize:13,fontWeight:600,cursor:"pointer"}}>Reset all feature flags</button>);
p(                <button style={{padding:"8px 16px",background:"transparent",border:"1px solid "+c.danger,borderRadius:8,color:c.danger,fontSize:13,fontWeight:600,cursor:"pointer"}}>Clear audit log</button>);
p(                <button style={{padding:"8px 16px",background:"transparent",border:"1px solid "+c.danger,borderRadius:8,color:c.danger,fontSize:13,fontWeight:600,cursor:"pointer"}}>Export all data</button>);
p(              </div>);
p(            </div>);
p(          </div>);
p(        )});
p(`);
p(      </main>);
p(`);
p(      {createOpen&&();
p(        <Modal title="Create new account" onClose={()=>setCreateOpen(false)} c={c} wide>);
p(          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 20px"}}>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Organisation logo" c={c}><LogoUploader current={form.logoUrl} onUpload={url=>setForm(f=>({...f,logoUrl:url}))} c={c}/></Field></div>);
p(            <Field label="Organisation name" required c={c}><input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Acme Corp" style={inp(c)}/></Field>);
p(            <Field label="URL handle" required c={c}><input value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value.toLowerCase().replace(/\s+/g,"-")}))} placeholder="acme-corp" style={inp(c)}/></Field>);
p(            <Field label="Owner email" required c={c}><input value={form.ownerEmail} onChange={e=>setForm(f=>({...f,ownerEmail:e.target.value}))} placeholder="owner@acme.com" style={inp(c)}/></Field>);
p(            <Field label="Owner name" c={c}><input value={form.ownerName} onChange={e=>setForm(f=>({...f,ownerName:e.target.value}))} placeholder="Jane Smith" style={inp(c)}/></Field>);
p(            <Field label="Owner phone" c={c}><input value={form.ownerPhone} onChange={e=>setForm(f=>({...f,ownerPhone:e.target.value}))} placeholder="+1 555 000 0000" style={inp(c)}/></Field>);
p(            <Field label="Website" c={c}><input value={form.website} onChange={e=>setForm(f=>({...f,website:e.target.value}))} placeholder="https://acme.com" style={inp(c)}/></Field>);
p(            <Field label="Address" c={c}><input value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))} placeholder="123 Main St" style={inp(c)}/></Field>);
p(            <Field label="Tax / VAT ID" c={c}><input value={form.taxId} onChange={e=>setForm(f=>({...f,taxId:e.target.value}))} placeholder="US123456789" style={inp(c)}/></Field>);
p(            <Field label="Plan" c={c}><select value={form.plan} onChange={e=>setForm(f=>({...f,plan:e.target.value as Plan}))} style={{...inp(c),cursor:"pointer"}}>{planDefs.map(pp=><option key={pp.id} value={pp.id}>{pp.name}</option>)}</select></Field>);
p(            <Field label="Max users" c={c}><input value={form.maxUsers} onChange={e=>setForm(f=>({...f,maxUsers:e.target.value}))} placeholder="50" style={inp(c)}/></Field>);
p(            <Field label="Max locations" c={c}><input value={form.maxLocations} onChange={e=>setForm(f=>({...f,maxLocations:e.target.value}))} placeholder="5" style={inp(c)}/></Field>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Admin notes" c={c}><textarea value={form.adminNotes} onChange={e=>setForm(f=>({...f,adminNotes:e.target.value}))} placeholder="Internal notes..." style={{...inp(c),minHeight:70,resize:"vertical"}}/></Field></div>);
p(            <div style={{gridColumn:"1/-1"}}><div style={{background:c.surfaceEl,border:"1px solid "+c.border,borderRadius:8,padding:"10px 14px",fontSize:12,color:c.textSub}}>Account starts on a 14-day trial automatically.</div></div>);
p(          </div>);
p(          <ModalFooter><SecBtn onClick={()=>setCreateOpen(false)} c={c}>Cancel</SecBtn><PriBtn disabled={submitting||!form.name||!form.slug||!form.ownerEmail} onClick={handleCreate} c={c}>{submitting?"Creating...":"Create account"}</PriBtn></ModalFooter>);
p(        </Modal>);
p(      )});
p(`);
p(      {editOrg&&();
p(        <Modal title={"Edit - "+editOrg.name} onClose={()=>setEditOrg(null)} c={c} wide>);
p(          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 20px"}}>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Logo" c={c}><LogoUploader current={editForm.logoUrl} onUpload={url=>setEditForm((f:any)=>({...f,logoUrl:url}))} c={c}/></Field></div>);
p(            <Field label="Organisation name" required c={c}><input value={editForm.name} onChange={e=>setEditForm((f:any)=>({...f,name:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Slug" c={c}><input value={editForm.slug} onChange={e=>setEditForm((f:any)=>({...f,slug:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Owner email" c={c}><input value={editForm.ownerEmail} onChange={e=>setEditForm((f:any)=>({...f,ownerEmail:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Owner name" c={c}><input value={editForm.ownerName} onChange={e=>setEditForm((f:any)=>({...f,ownerName:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Owner phone" c={c}><input value={editForm.ownerPhone} onChange={e=>setEditForm((f:any)=>({...f,ownerPhone:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Website" c={c}><input value={editForm.website} onChange={e=>setEditForm((f:any)=>({...f,website:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Address" c={c}><input value={editForm.address} onChange={e=>setEditForm((f:any)=>({...f,address:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Tax / VAT ID" c={c}><input value={editForm.taxId} onChange={e=>setEditForm((f:any)=>({...f,taxId:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Max users" c={c}><input value={editForm.maxUsers} onChange={e=>setEditForm((f:any)=>({...f,maxUsers:e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Max locations" c={c}><input value={editForm.maxLocations} onChange={e=>setEditForm((f:any)=>({...f,maxLocations:e.target.value}))} style={inp(c)}/></Field>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Admin notes" c={c}><textarea value={editForm.adminNotes} onChange={e=>setEditForm((f:any)=>({...f,adminNotes:e.target.value}))} style={{...inp(c),minHeight:70,resize:"vertical"}}/></Field></div>);
p(          </div>);
p(          <ModalFooter><SecBtn onClick={()=>setEditOrg(null)} c={c}>Cancel</SecBtn><PriBtn disabled={submitting} onClick={handleEdit} c={c}>{submitting?"Saving...":"Save changes"}</PriBtn></ModalFooter>);
p(        </Modal>);
p(      )});
p(`);
p(      {planEditIdx!==null&&planEditVal&&();
p(        <Modal title={planEditIdx<planDefs.length?"Edit plan - "+(planDefs[planEditIdx]?.name??""):"New plan"} onClose={()=>{setPlanEditIdx(null);setPlanEditVal(null);}} c={c} wide>);
p(          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 20px"}}>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Plan name" required c={c}><input value={planEditVal.name} onChange={e=>setPlanEditVal((p:any)=>({...p,name:e.target.value}))} style={inp(c)}/></Field></div>);
p(            <div style={{gridColumn:"1/-1"}}><Field label="Description" c={c}><input value={planEditVal.desc} onChange={e=>setPlanEditVal((p:any)=>({...p,desc:e.target.value}))} style={inp(c)}/></Field></div>);
p(            <Field label="Monthly price ($)" c={c}><input type="number" value={planEditVal.price} onChange={e=>setPlanEditVal((p:any)=>({...p,price:+e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Annual price ($/mo)" c={c}><input type="number" value={planEditVal.annualPrice} onChange={e=>setPlanEditVal((p:any)=>({...p,annualPrice:+e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Max users" c={c}><input type="number" value={planEditVal.maxUsers} onChange={e=>setPlanEditVal((p:any)=>({...p,maxUsers:+e.target.value}))} style={inp(c)}/></Field>);
p(            <Field label="Max locations" c={c}><input type="number" value={planEditVal.maxLocations} onChange={e=>setPlanEditVal((p:any)=>({...p,maxLocations:+e.target.value}))} style={inp(c)}/></Field>);
p(            <div style={{gridColumn:"1/-1"}}>);
p(              <Field label="Accent colour" c={c}>);
p(                <div style={{display:"flex",gap:8,alignItems:"center"}}>);
p(                  <input type="color" value={planEditVal.color} onChange={e=>setPlanEditVal((p:any)=>({...p,color:e.target.value}))} style={{width:40,height:36,borderRadius:6,border:"1px solid "+c.border,cursor:"pointer"}}/>);
p(                  <input value={planEditVal.color} onChange={e=>setPlanEditVal((p:any)=>({...p,color:e.target.value}))} style={{...inp(c),flex:1}}/>);
p(                </div>);
p(              </Field>);
p(            </div>);
p(            <div style={{gridColumn:"1/-1"}}>);
p(              <div style={{fontSize:12,fontWeight:600,color:c.textSub,marginBottom:10,textTransform:"uppercase" as const,letterSpacing:"0.06em"}}>Features included in this plan</div>);
p(              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>);
p(                {FEATURES.map(f=>();
p(                  <div key={f.key} onClick={()=>setPlanEditVal((p:any)=>({...p,features:{...p.features,[f.key]:!p.features?.[f.key]}}))} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"10px 14px",borderRadius:8,border:"1px solid "+(planEditVal.features?.[f.key]?planEditVal.color:c.border),background:planEditVal.features?.[f.key]?"rgba(34,197,94,0.06)":c.surfaceEl,cursor:"pointer",transition:"all .15s"}}>);
p(                    <div><div style={{fontSize:13,fontWeight:600,color:planEditVal.features?.[f.key]?c.text:c.textSub}}>{f.label}</div><div style={{fontSize:10,color:c.textMute}}>{f.desc}</div></div>);
p(                    <Toggle on={!!planEditVal.features?.[f.key]} onChange={()=>setPlanEditVal((p:any)=>({...p,features:{...p.features,[f.key]:!p.features?.[f.key]}}))} c={c}/>);
p(                  </div>);
p(                ))});
p(              </div>);
p(            </div>);
p(          </div>);
p(          <ModalFooter>);
p(            {planEditIdx<planDefs.length&&<button onClick={()=>{setPlanDefs(d=>d.filter((_,i)=>i!==planEditIdx));setPlanEditIdx(null);setPlanEditVal(null);}} style={{marginRight:"auto",padding:"9px 14px",borderRadius:8,border:"none",background:c.dangerBg,color:c.danger,fontSize:13,fontWeight:600,cursor:"pointer"}}>Delete plan</button>});
p(            <SecBtn onClick={()=>{setPlanEditIdx(null);setPlanEditVal(null);}} c={c}>Cancel</SecBtn>);
p(            <PriBtn onClick={savePlanEdit} c={c} disabled={!planEditVal.name}>{planEditIdx<planDefs.length?"Save plan":"Create plan"}</PriBtn>);
p(          </ModalFooter>);
p(        </Modal>);
p(      )});
p(`);
p(      {blockModal&&();
p(        <Modal title={blockModal.status==="blocked"?"Unblock organisation":"Block organisation"} onClose={()=>{setBlockModal(null);setBlockReason("");}} c={c}>);
p(          <div style={{fontSize:15,fontWeight:700,marginBottom:14,color:c.text}}>{blockModal.name}</div>);
p(          {blockModal.status!=="blocked"?<Field label="Reason (optional)" c={c}><textarea value={blockReason} onChange={e=>setBlockReason(e.target.value)} placeholder="e.g. Payment failed..." style={{...inp(c),minHeight:80,resize:"vertical"}}/></Field>:<p style={{fontSize:13,color:c.textSub}}>This will restore full access for all users in this organisation.</p>});
p(          <ModalFooter><SecBtn onClick={()=>{setBlockModal(null);setBlockReason("");}} c={c}>Cancel</SecBtn><PriBtn onClick={handleBlockToggle} disabled={submitting} c={c} danger={blockModal.status!=="blocked"}>{submitting?"...":blockModal.status==="blocked"?"Unblock":"Block organisation"}</PriBtn></ModalFooter>);
p(        </Modal>);
p(      )});
p(`);
p(      {deleteConfirm&&();
p(        <Modal title="Delete organisation" onClose={()=>setDeleteConfirm(null)} c={c}>);
p(          <div style={{fontSize:15,fontWeight:700,marginBottom:12,color:c.text}}>{deleteConfirm.name}</div>);
p(          <div style={{background:c.dangerBg,border:"1px solid rgba(239,68,68,0.25)",borderRadius:8,padding:"12px 14px",fontSize:13,color:c.danger}}>Permanent and cannot be undone. All data for this organisation will be deleted forever.</div>);
p(          <ModalFooter><SecBtn onClick={()=>setDeleteConfirm(null)} c={c}>Cancel</SecBtn><PriBtn onClick={handleDelete} disabled={submitting} c={c} danger>{submitting?"Deleting...":"Delete permanently"}</PriBtn></ModalFooter>);
p(        </Modal>);
p(      )});
p(`);
p(    </div>);
p(  ););
p(});
p(`);
const content = lines.join('\n');
require('fs').writeFileSync('src/features/superadmin/pages/SuperAdminPage.tsx', content, {encoding:'utf8',flag:'w'});
console.log('Written OK - ' + lines.length + ' lines');
